import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';

/* README constraint contract
 * Project README, focused showpiece: the top third is a compact instrument
 * panel. Two real client inputs converge on the same line-numbered outline.
 * Keep installation immediately beneath it; prose stays ordinary Markdown.
 * Use the site's carbon / vellum / phosphor palette and system fonts only.
 * Four compositions: wide/narrow x light/dark. Phone art is recomposed, never
 * a shrunken desktop. No scripts, remote assets, hover, or invisible text.
 * Motion loops on the connectors only. Static connectors and every label
 * remain legible at all times, including prefers-reduced-motion.
 * Facts: client adapters from HookTarget, threshold from Config::default,
 * and the three example declaration line numbers from src/main.rs.
 * No adoption claims, historical savings percentages, or invented metrics.
 */
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const read = p => new TextDecoder('utf-8', { fatal: true }).decode(fs.readFileSync(path.join(root, p)));
const check = process.argv.includes('--check');
const main = read('src/main.rs');
const targets = main.match(/enum HookTarget\s*\{([\s\S]*?)\n\}/)?.[1];
assert(targets, 'HookTarget enum missing');
const clients = [...targets.matchAll(/^\s*([A-Z][A-Za-z0-9_]*),/gm)].map(m => m[1]);
assert.deepEqual(clients, ['Claude', 'Codex'], 'Update artwork for the actual client inventory');
const threshold = Number(read('src/config.rs').match(/clamp_threshold:\s*(\d+),/)?.[1]);
assert(Number.isSafeInteger(threshold) && threshold > 0 && threshold % 1024 === 0);
const declarations = ['struct Cli', 'enum Command', 'fn main'].map(symbol => {
  const line = main.split(/\r?\n/).findIndex(l => l.startsWith(symbol)) + 1;
  assert(line > 0, `Missing example declaration: ${symbol}`);
  return { symbol, line };
});
const esc = s => String(s).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('"', '&quot;');
const themes = {
  dark: { bg: '#0B0C0E', ink: '#EDE6D6', mute: '#A3A39A', rule: '#363C40', panel: '#15181B', accent: '#FFB454' },
  light: { bg: '#F3EEE3', ink: '#242422', mute: '#68665E', rule: '#C8C1B4', panel: '#FFFCF6', accent: '#9A4900' },
};
const marker = '<!-- Generated by scripts/readme/build.mjs; edit the generator. -->';

function panel(t, narrow) {
  const W = narrow ? 360 : 880, H = narrow ? 402 : 310;
  const text = (x, y, label, size = 12, color = t.ink, more = '') => `<text x="${x}" y="${y}" font-size="${size}" fill="${color}" ${more}>${esc(label)}</text>`;
  const rule = (x1, y1, x2, y2) => `<path d="M${x1} ${y1}H${x2}" stroke="${t.rule}"/>`;
  const box = (x, y, w, h) => `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="3" fill="${t.panel}" stroke="${t.rule}"/>`;
  const flow = d => `<path d="${d}" fill="none" stroke="${t.rule}"/><path class="flow" d="${d}" fill="none" stroke="${t.accent}" stroke-width="2"/>`;
  let body;
  if (narrow) {
    body = text(22, 30, 'SESSION TOKEN KILLER', 10, t.mute, 'letter-spacing="1.7"')
      + text(16, 117, 'STK', 100, t.ink, 'font-weight="750" letter-spacing="-8"')
      + text(22, 155, 'The file, in outline.', 26, t.ink, 'class="sans" font-weight="650" letter-spacing="-1"')
      + text(22, 181, 'Read only what the task needs.', 14, t.mute, 'class="sans"')
      + box(22, 207, 144, 34) + text(34, 229, 'Claude Code', 13)
      + box(194, 207, 144, 34) + text(207, 229, 'Codex', 13)
      + flow('M94 241V252H180V267') + flow('M266 241V252H180')
      + box(22, 268, 316, 91) + text(34, 288, 'src/main.rs', 10, t.mute)
      + declarations.map((d, i) => text(34, 309 + i * 18, String(d.line).padStart(3), 12, t.accent, 'xml:space="preserve"') + text(75, 309 + i * 18, d.symbol, 12)).join('')
      + text(22, 385, 'ONE BINARY', 10, t.mute, 'letter-spacing="1"')
      + text(338, 385, `DEFAULT > ${threshold / 1024} KiB`, 10, t.mute, 'text-anchor="end"');
  } else {
    body = text(30, 35, 'SESSION TOKEN KILLER', 11, t.mute, 'letter-spacing="2"')
      + text(21, 173, 'STK', 152, t.ink, 'font-weight="750" letter-spacing="-12"')
      + text(32, 220, 'ONE BINARY', 11, t.accent, 'letter-spacing="1.8"')
      + text(32, 245, 'Claude Code + Codex', 15, t.mute, 'class="sans"')
      + text(350, 72, 'The file, in outline.', 36, t.ink, 'class="sans" font-weight="650" letter-spacing="-1.4"')
      + text(350, 103, 'Read only what the task needs.', 17, t.mute, 'class="sans"')
      + box(350, 142, 145, 38) + text(364, 166, 'Claude Code', 13)
      + box(350, 205, 145, 38) + text(364, 229, 'Codex', 13)
      + flow('M495 161H545V192H595') + flow('M495 224H545V192')
      + `<circle cx="545" cy="192" r="3" fill="${t.accent}"/>`
      + box(595, 142, 253, 101) + text(609, 162, 'src/main.rs', 10, t.mute)
      + declarations.map((d, i) => text(609, 184 + i * 20, String(d.line).padStart(3), 13, t.accent, 'xml:space="preserve"') + text(655, 184 + i * 20, d.symbol, 13)).join('')
      + rule(32, 272, 848, 272)
      + text(32, 294, 'OVERSIZED READ / OUTLINE / TARGETED LINES', 10, t.mute, 'letter-spacing="1"')
      + text(848, 294, `DEFAULT > ${threshold / 1024} KiB`, 10, t.mute, 'text-anchor="end"');
  }
  return `${marker}
<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" role="img" aria-labelledby="title desc">
<title id="title">STK: Session Token Killer</title>
<desc id="desc">Claude Code and Codex share one outline engine. Files above the default ${threshold / 1024} KiB threshold can become line-numbered outlines, with content available through targeted reads. The example declarations come from src/main.rs.</desc>
<style>
text{font-family:ui-monospace,'Cascadia Mono',Consolas,'Liberation Mono',monospace}
.sans{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif}
.flow{stroke-dasharray:16 210;animation:travel 6s linear infinite}
@keyframes travel{from{stroke-dashoffset:226}to{stroke-dashoffset:0}}
@media(prefers-reduced-motion:reduce){.flow{animation:none;stroke-dasharray:none;stroke-dashoffset:0;opacity:.45}}
</style>
<rect x=".5" y=".5" width="${W - 1}" height="${H - 1}" rx="4" fill="${t.bg}" stroke="${t.rule}"/>
${body}
</svg>
`;
}

for (const [theme, tokens] of Object.entries(themes)) {
  for (const narrow of [false, true]) {
    const file = `assets/readme/hero-${narrow ? 'narrow-' : ''}${theme}.svg`;
    const svg = panel(tokens, narrow);
    assert(!/<script|<foreignObject|https?:\/\//.test(svg.replace('http://www.w3.org/2000/svg', '')));
    for (const { line, symbol } of declarations) {
      assert(svg.includes(`>${esc(symbol)}</text>`));
      assert(svg.includes(`>${String(line).padStart(3)}</text>`));
    }
    assert(svg.includes('prefers-reduced-motion') && svg.includes('infinite'));
    if (check) assert.equal(read(file), svg, `${file} is stale; run node scripts/readme/build.mjs`);
    else {
      fs.mkdirSync(path.dirname(path.join(root, file)), { recursive: true });
      fs.writeFileSync(path.join(root, file), svg);
    }
  }
}

const readme = read('README.md');
assert(readme.startsWith('<!-- readme-art: scripts/readme/build.mjs -->'), 'Art marker missing');
for (const required of ['## Install', '## Use it', '## Verified behavior', 'cargo install --path .', 'stk init --auto', 'docs/usage.md', 'docs/dual-client-verification.md', 'LICENSE']) {
  assert(readme.includes(required), `README lost ${required}`);
}
assert(readme.indexOf('## Install') < 1600, 'Installation moved below the README floor');
const sources = [...readme.matchAll(/(?:src|srcset)="([^"#]+)"/g)].map(m => m[1]);
assert.equal(sources.length, 4, 'Hero requires four theme/viewport variants');
assert(sources[0].includes('narrow-dark') && sources[1].includes('narrow-light'), 'Narrow sources must come first');
for (const file of sources) assert(fs.existsSync(path.join(root, file)), `Missing image ${file}`);
for (const [client, source] of [['Claude Code', 'src/hook.rs'], ['Codex', 'src/codex.rs']]) {
  assert.equal(readme.split(`| [${client}](${source}) |`).length - 1, 1, `Expected one linked coverage row for ${client}`);
}
for (const [, link] of readme.matchAll(/\]\(([^)]+)\)/g)) {
  if (!/^(https?:|#)/.test(link)) assert(fs.existsSync(path.join(root, link.split('#')[0])), `Broken local link: ${link}`);
}
console.log(`README ${check ? 'verified' : 'built'}: ${clients.length} adapters, ${threshold / 1024} KiB default, 4 variants, ${declarations.length} source-derived declarations.`);
